// Shared options dan helper untuk mapping potensi_bahaya (Take 5) ke ketidaksesuaian (Hazard)

export const SUB_OPTIONS = {
  APD: [
    "Cara Penggunaan APD",
    "Kesesuaian dan Kelayakan APD",
    "Pengawas Tidak Memastikan Kesesuaian dan Kelayakan APD Pekerja Saat Aktivitas Telah Berlangsung",
    "Tidak Menggunakan APD",
  ],
  "Area Parkir": [
    "Area Parkir tidak aman dari radius unit hauler",
    "Jarak parkir unit tidak standar",
    "Kendaraan/Unit Parkir di Area yang Tidak Rata",
    "Pengawas Tidak Memasang Rambu Parkir saat Aktivitas Telah Berlangsung",
    "Tidak Ada Area Parkir",
    "Tidak ada Perbaikan Area Parkir yang Tidak Rata",
    "Tidak ada Rambu Parkir",
    "Tidak ada Stopper",
    "Tidak tersedia pembatas antar unit",
  ],
  "Bahaya Peledakan": [
    "Akses Menuju lokasi peledakan/gudang handak tidak layak",
    "Area manuver MMU / Anfo Truck tidak memadai",
    "Area penyimpanan bahan peledak pada lokasi peledakan tidak di atur dengan baik",
    "Box unit pengangkut bahan peledak tidak digembok",
    "High/Low wall & crest area peledakan tidak aman",
    "Jarak lubang ledak terhadap jalan aktif terlalu dekat",
    "Jarak unit drilling terlalu dekat dengan MMU/ Anfo Truck",
    "Jumlah unit yang dikawal melebihi batas jumlah yang diperbolehkan",
    "Kemiringan jalan akses masuk area peledakan > 10%",
    "Kondisi permukaan jalan akses peledakan tidak Keras/Kering/bergelombang/rata",
    "Lebar jalan akses masuk area peledakan <8 meter",
    "Lokasi peledakan dan pengeboran tidak diberi jarak/batas",
    "Lokasi Teras Area Peledakan tidak memadai",
    "Lubang tidak di sounding sebelum melakukan pengisian",
    "Man Power yang bekerja pada area peledakan tidak memiliki lisensi/ lisensi expired",
    "Melakukan pemuatan dan pengangkutan bahan peledak tanpa Juru Ledak",
    "Melakukan pemuatan dan pengangkutan bahan peledak tanpa pengawalan",
    "Melakukan pemuatan dan pengangkutan bahan peledak tanpa pengamanan",
    "Pengisian Bahan peledak overcharge",
    "Tanggul lokasi peledakan tidak sesuai standar",
    "Terdapat lubang collapse/Lumpur/Miring",
    "Terdapat Lubang Panas/Reaktif pada Area Peledakan",
    "Terdapat Material Menggantung",
  ],
  "Bahaya Biologi": [
    "Bahaya hewan buas",
    "Pengawas gagal mengidentifikasi bahaya biologis",
    "Pohon kering",
    "Serangga",
    "Terdapat tanamanan merambat yang lebat diarea kerja yang berpotensi menjadi sarang ular",
    "Tidak melakukan pemeliharaan rumput liar di area kerja",
  ],
  "Bahaya Elektrikal": [
    "Instalasi listrik tidak layak",
    "Kabel tidak layak",
    "Pengamanan peralatan listrik",
    "Pengawas tidak melakukan pengamanan peralatan listrik",
    "Pengawas tidak memastikan kelayakan instalasi listrik saat aktivitas telah berlangsung",
    "Pengawas tidak mengidentifikasi potensi arus pendek saat aktivitas telah berlangsung",
    "Potensi arus pendek",
  ],
  "External Issue": ["External Issue"],
  "Fasilitas Mixing Plant": [
    "Filter rusak",
    "Generator Rusak",
    "Penerangan Tidak Standar",
    "Peralatan belum dilakukan kalibrasi",
    "Tidak ada penerangan",
    "Tidak dilakukan perawatan rutin peralatan",
  ],
  "Fasilitas Office": [
    "Area Merokok tidak bersih",
    "Pantry Tidak Bersih",
    "Peralatan listrik belum dilakukan inspeksi berkala",
    "Penerangan Tidak standar",
    "Tidak ada penerangan",
    "Toilet Rusak",
  ],
  "Fasilitas Workshop": [
    "Lifting gear tidak ditagging",
    "Pad workshop kotor",
    "Penerangan Tidak standar",
    "Saluran Air / Drainase tidak ada",
    "Saluran Air / Drainase untuk fasilitas workshop tersumbat",
    "Tidak ada Penerangan",
  ],
  "Izin Kerja": [
    "Izin Bekerja Ruang Terbatas Expired",
    "Izin Bekerja Ruang Terbatas Tidak Sesuai",
    "Izin Bekerja Ruang Terbatas Tidak Tersedia",
    "Izin Bekerja diketinggian Expired",
    "Izin Bekerja diketinggian Tidak Tersedia",
    "Izin Bekerja diketinggian tidak sesuai",
    "Izin Kerja Panas Expired",
    "Izin Kerja Panas Tidak Tersedia",
    "Izin Kerja panas Tidak Sesuai",
  ],
  "Kelayakan Bangunan": ["Bangunan Rusak", "Kelayakan Bangunan"],
  "Kelayakan Tools": [
    "Kelayakan Common Tools",
    "Kelayakan Lifting Gear",
    "Kelayakan Small Equipment / Power Tools",
    "Kelayakan Special Tools",
    "Kelayakan Supporting Tools",
    "Kesesuaian Penggunaan Common Tools",
    "Kesesuaian Penggunaan Lifting Gear",
    "Kesesuaian Penggunaan Small Equipment / Power Tools",
    "Kesesuaian Penggunaan Special Tools",
    "Kesesuaian Penggunaan Supporting Tools",
    "Pelabelan/Penandaan Lifting Gear",
    "Pelabelan/Penandaan Small Equipment / Power Tools",
    "Pelabelan/Penandaan Special Tools",
    "Pelabelan/Penandaan Supporting Tools",
  ],
  "Kelengkapan Tanggap Darurat": [
    "Alat Tanggap Darurat Belum Dilakukan Inspeksi",
    "Emergency Alarm Tidak Berfungsi",
    "Eye Wash",
    "Fire Apparatus",
    "Fire Suspression",
    "Jalur Evakuasi",
    "Kelengkapan P3K",
    "Pengawas Tidak Melakukan Inspeksi Alat Tanggap Darurat",
    "Pengawas Tidak Memeriksa Kelayakan Eyewash",
    "Refill APAR",
  ],
  "Kondisi Fisik Pekerja": [
    "Cidera atau sakit yang dialami sebelumnya",
    "Kekurangan Gula Darah",
    "Kelelahan karena Beban Kerja",
    "Kelelahan Karena Kurang Istirahat",
    "Sakit Akibat Mengkonsumsi Obat-obatan Terlarang atau minuman keras",
    "Unjuk Kerja menurun karena tingginya temperatur",
  ],
  "Kondisi Kendaraan/Unit": [
    "Kelayakan Kendaraan/Unit",
    "Mengoperasikan Kendaraan/Unit Yang Tidak Layak",
    "Tidak Melakukan P2H",
  ],
  "Lingkungan Kerja": [
    "Bahan Kimia yang Berbahaya",
    "Ceceran B3",
    "Getaran",
    "Kabut",
    "Kebisingan",
    "Lingkungan Berdebu",
    "Pencahayaan",
    "Pengawas Tidak Memastikan Pencahayaan yang Standard Sebelum Aktivitas Berlangsung",
    "Radiasi",
    "Suhu Panas/dingin",
    "Swabakar",
    "Ventilasi Tidak Memadai",
  ],
  Penandaan: [
    "Barikade/ Safety line",
    "Demarkasi",
    "Ketidaksesuaian LOTO",
    "Kode Warna",
    "Labeling Tidak Ada",
    "Labeling Tidak Standar / Sesuai",
    "Pengawas Tidak Membuat Demarkasi Saat Aktivitas Telah Berlangsung",
    "Pengawas Tidak Memasang Barikade / Safety Line saat Aktivitas Telah Berlangsung",
    "Pengawas Tidak Memberikan Kode Pewarnaan yang standar Saat Aktivitas Telah Berlangsung",
    "Pita Batas Radius Peledakan/ Sleepblast tidak ada",
    "Tidak Memasang LOTO",
  ],
  Rambu: [
    "Kelayakan Rambu",
    "Lampu Flip Flop Area Sleepblast belum Ada",
    "Pengawas Tidak Melakukan Perawatan rambu Sehingga Rambu Menjadi Tidak Layak",
    "Pengawas Tidak Memasang Rambu Yang Memadai Saat Aktivitas Telah Berlangsung",
    "Pengawas Tidak Memasang Rambu Yang Sesuai saat Aktivitas Telah Berlangsung",
    "Posisi Rambu Tidak Sesuai",
    "Rambu Aktivitas Peledakan Tidak Terpasang",
    "Rambu APD",
    "Tidak Ada Rambu",
    "Tidak Terdapat Rambu Atau Bendera Radius Aman Manusia",
    "Unit Breakdown Tanpa Alat Pengaman dan Rambu",
  ],
  "Tools Inspection": [
    "Tidak Ada Penjadwalan Tools Inspection untuk Suatu Area Pekerjaan",
    "Tools Belum Dilakukan Inspeksi",
  ],
};

export function matchPotensiBahayaToKetidaksesuaian(potensiBahaya, subOptions = SUB_OPTIONS) {
  if (!potensiBahaya || typeof potensiBahaya !== "string") return { ketidaksesuaian: "", subKetidaksesuaian: "" };
  const pb = potensiBahaya.trim();
  if (!pb) return { ketidaksesuaian: "", subKetidaksesuaian: "" };
  const cats = Object.keys(subOptions || {});
  const exactCat = cats.find((c) => c.toLowerCase() === pb.toLowerCase());
  if (exactCat) return { ketidaksesuaian: exactCat, subKetidaksesuaian: "" };
  for (const cat of cats) {
    const subs = subOptions[cat] || [];
    const found = subs.find((s) => s.toLowerCase() === pb.toLowerCase());
    if (found) return { ketidaksesuaian: cat, subKetidaksesuaian: found };
  }
  return { ketidaksesuaian: "", subKetidaksesuaian: "" };
}
