-- SQL untuk membuat tabel pengecekan versi aplikasi
-- Jalankan script ini di SQL Editor Supabase Anda

-- 1. Buat tabel app_versions
CREATE TABLE IF NOT EXISTS app_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL, -- 'android', 'ios'
  latest_version TEXT NOT NULL,
  force_update BOOLEAN DEFAULT FALSE,
  message TEXT,
  store_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tambahkan constraint unique untuk platform agar tidak duplikat
ALTER TABLE app_versions ADD CONSTRAINT app_versions_platform_key UNIQUE (platform);

-- 3. Masukkan data awal untuk Android (sesuaikan versi dengan package.json saat ini: 1.0.0)
-- Jika nanti Anda merilis versi 1.0.1, update row ini.
INSERT INTO app_versions (platform, latest_version, force_update, message, store_url)
VALUES 
  ('android', '1.0.0', false, 'Pembaruan tersedia. Silakan update aplikasi Anda untuk fitur terbaru.', 'https://play.google.com/store/apps/details?id=com.example.app')
ON CONFLICT (platform) DO NOTHING;

-- 4. Masukkan data awal untuk iOS (jika perlu)
INSERT INTO app_versions (platform, latest_version, force_update, message, store_url)
VALUES 
  ('ios', '1.0.0', false, 'Pembaruan tersedia. Silakan update aplikasi Anda.', 'https://apps.apple.com/app/id123456789')
ON CONFLICT (platform) DO NOTHING;

-- 5. Aktifkan RLS (Row Level Security) agar aman
ALTER TABLE app_versions ENABLE ROW LEVEL SECURITY;

-- 6. Buat policy agar semua user (authenticated & anon) bisa MEMBACA (SELECT) data versi
-- Kita izinkan anon karena pengecekan versi mungkin terjadi di halaman Login sebelum user masuk
CREATE POLICY "Allow public read access" ON app_versions
  FOR SELECT USING (true);

-- 7. Buat policy agar hanya service_role (atau admin tertentu) yang bisa UPDATE/INSERT
-- (Secara default, jika tidak ada policy FOR INSERT/UPDATE, maka tidak ada yang bisa kecuali service_role)

-- Selesai.
-- Cara Update Versi Nanti:
-- UPDATE app_versions 
-- SET latest_version = '1.1.0', force_update = true, message = 'Update Wajib: Perbaikan Bug Kritis'
-- WHERE platform = 'android';
